version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: namaste_bali_panel_api
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env
    ports:
      - "8282:8080"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'certbot certonly --webroot --webroot-path=/var/www/html --email your-email@example.com --agree-tos --no-eff-email -d api.namastebalitrans.com && sleep infinity'"
    depends_on:
      - nginx