version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: namaste_bali_panel_api
    volumes:
      - ./Uploads:/app/uploads
    env_file:
      - .env
    ports:
      - "8282:8080"
    restart: unless-stopped